### ISSUE TITLE
Necro sees ragdolls on his radar

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_necro#1]
On certain maps, while being Necromancer, it happened that I saw the map ragdoll corpses as players I could revive on my radar

![Half Life  Source Screenshot 2019 12 24 - 19 14 12 87](https://user-images.githubusercontent.com/36534723/71423112-52cf9e00-2687-11ea-84bf-f3092e82361f.png)

**Comment by Alf21** [comment]
It‘s intended that the necro‘s radar just detects corpses.

**Comment by TimGoll** [comment]
I think he talks about map ragdolls, like the dead players in some maps. One could check if the ragdoll has a role for example

**Comment by ThePlatinumGhost** [comment]
Yes i'm talking about map ragdoll, sorry if I expressed myself wrong

**Comment by saibotk** [comment]
@ThePlatinumGhost should be fixed, otherwise please let us know here. 
Thank you for your report! :+1:
