### ISSUE TITLE
Necromancer disguiser bug

### ISSUE THREAD

**Issue by MisterClems** [TTT-2/ttt2-role_necro#18]
We only can activate the disguiser with the T shop , the key bind with  ttt2_disguiser_toggle didnt work when we are Necromancer but still work when we are traitor

On the latest github version for TTT2 and Necro

**Comment by TimGoll** [comment]
I'm not 100% sure that I know what you're talking about

**Comment by MisterClems** [comment]
We only can activate the disguiser with this when we are necromancer
![Capture d’écran 2021-05-14 233606](https://user-images.githubusercontent.com/73431903/118334123-3eef3b00-b50d-11eb-9ce7-c3b6b9c11232.png)

The key bind for the disguiser dont work only when we are necromancer 
![Capture d’écran 2021-05-14 233528](https://user-images.githubusercontent.com/73431903/118334175-5d553680-b50d-11eb-9cc1-95c948aa6a7b.png)

**Comment by TimGoll** [comment]
Ahh, that's understandable. Thanks for the report

**Comment by TimGoll** [comment]
fixed in dev of TTT2
