### ISSUE TITLE
Round Report Screen : Necromancer revive event icon doesnt display

### ISSUE THREAD

**Issue by MisterClems** [TTT-2/ttt2-role_necro#21]
When the necromancer revive a player on the round report screen we have this : 
![Capture d’écran 2021-06-10 145438](https://user-images.githubusercontent.com/73431903/121532856-08b7b500-ca00-11eb-9cc2-814e8c7553b1.png)

**Comment by TimGoll** [comment]
![image](https://user-images.githubusercontent.com/13639408/136673314-b917b1c1-4ab9-49a0-bada-bbb5ce222ea8.png)

I can't confirm that. Does this error still happen for you? Please reopen if it still persists.
