### ISSUE TITLE
"ttt2_zomb_maxhealth_new_zomb" problem

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_necro#3]
Changing the value of "ttt2_zomb_maxhealth_new_zomb" does not work
Even if I change the value the new zombies spawn with 100 hp
Video https://youtu.be/ivry7GS2e5c

**Comment by TimGoll** [comment]
Yes, I think I alreaady found the issue, I test it right now

**Comment by TimGoll** [comment]
fixed in dev
