### ISSUE TITLE
Change the zombie model of the Necromancer

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2-role_necro#4]
This is a suggestion, but the necromancer zombie model could be changed to differentiate it from the infected zombie, that are the same
For example, it could become a skeleton, like this 
![skel](https://user-images.githubusercontent.com/36534723/80124773-0c387480-8591-11ea-9515-87e0b28268cc.jpg)
the related sounds and the icon could obviously change
In the end at the plot level the necromancer often and willingly works with skeletons in many video games / story, that sound legit 
![image](https://user-images.githubusercontent.com/36534723/80124911-3f7b0380-8591-11ea-934a-57fab9fda669.png)
obviously of your choice, you can also refuse if you don't like the idea :)

**Comment by TimGoll** [comment]
I like the idea to use this model. But the licencing might be problematic

**Comment by ThePlatinumGhost** [comment]
What do you mean by "licencing "?

**Comment by TimGoll** [comment]
Is this model included in garrys mod? If it isn't, we have to add it ourselves. And we can't just add a random model from someone.

**Comment by ThePlatinumGhost** [comment]
yes it's included!

**Comment by ThePlatinumGhost** [comment]
models/player/skeleton.mdl

**Comment by TimGoll** [comment]
Good thing takes a while, after four years you now have the option to change the model. I hope you're still playing TTT :D

**Comment by ThePlatinumGhost** [comment]
Sadly I don't play TTT anymore except rarely, but is still a good things that now the option is now available
